spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

server:
  port: 8080

# AWS S3 설정
cloud:
  aws:
    s3:
      bucket: eos-blog-bucket
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2

# 로깅 설정
logging:
  level:
    com.eos.blog: DEBUG
    software.amazon.awssdk: DEBUG